version: '3.4'

services:
  app:
    image: wordcannon/service
    environment:
      LANGUAGE: english
      NUM_WORDS: 10000
      VOWEL_TRIGGER_COUNT: 4
  web:
    image: wordcannon/web
    ports:
        - 80:8888    
