version: '3.4'

services:
  app:
    image: wordcannon/service
    environment:
      LANGUAGE: english
      NUM_WORDS: 10000
      VOWEL_TRIGGER_COUNT: 4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/word"]
      interval: 5s
      timeout: 10s
      retries: 1    
  web:
    image: wordcannon/web
    ports:
        - 80:8888    
