apiVersion: v1
kind: Service
metadata:
  name: word-generator-service
  namespace: wordcannon
spec:
  selector:
    app: word-generator-app
  ports:
    - protocol: TCP
      port: 32789
      targetPort: 8080
  type: LoadBalancer
