apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordcannon-backend
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordcannon-backend
        tier: backend
    spec:
      containers:
      - name: app
        image: wordcannon/service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      env:
      - name: WORDCANNON_LANGUAGE
        value: "en_US"