apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web
        image: wordcannon/web
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
