apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wordcannon
spec:
  selector:
    app: frontend-app
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  type: LoadBalancer
