apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wordcannon
spec:
  selector:
    app: wordcannon-frontend
    tier: frontend
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  type: NodePort
