apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: production
spec:
  selector:
    app: wordcannon-frontend
    tier: frontend
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  type: LoadBalancer
  