apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      tier: backend
  serviceMonitorNamespaceSelector:
    matchLabels:
      name: production
  resources:
    requests:
      memory: 400Mi